# @package _global_

defaults:
  - classification_base

dataset:
  name: swissprot
  train_classes: 7195
  simple_cls:
    _target_: datasets.prot.swissprot.SPSimpleDataset

  set_cls:
    _target_: datasets.prot.swissprot.SPSetDataset

  backbone:
    name: FCNet
    _target_: backbones.fcnet.FCNet
    layer_dim: [512, 512]

