defaults:
  - classification_base

name: swissprot
train_classes: 7195
simple_cls:
  _target_: datasets.prot.swissprot.SPSimpleDataset

set_cls:
  _target_: datasets.prot.swissprot.SPSetDataset

backbone:
  name: FCNet
  feat_dim: 512
  _target_: backbones.fcnet.FCNet
