# @package _global_

defaults:
  - classification_base

dataset:
  name: tabula_muris
  train_classes: 59
  simple_cls:
    _target_: datasets.cell.tabula_muris.TMSimpleDataset

  set_cls:
    _target_: datasets.cell.tabula_muris.TMSetDataset

  backbone:
    name: FCNet
    _target_: backbones.fcnet.FCNet
    layer_dim: [64, 64]

