defaults:
  - traditional_base

name: baseline

cls:
  _target_: methods.baseline.Baseline
  type: ${dataset.type}
  n_way: ${n_way}
  n_support: ${n_shot}
  n_classes: ${dataset.train_classes}
  loss: softmax
