# @package _global_

defaults:
  - method_base

method:
  name: baseline
  type: baseline
  train_batch: 16

  cls:
    _target_: methods.baseline.Baseline
    type: ${dataset.type}
    n_way: ${exp.n_way}
    n_support: ${exp.n_shot}
    n_classes: ${dataset.train_classes}
    loss: softmax

train:
  stop_epoch: 40 # Number of epochs to train
