# @package _global_

defaults:
  - method_base

method:
  name: baseline
  type: baseline

  cls:
    _target_: methods.baseline.Baseline
    type: ${dataset.type}
    n_way: ${exp.n_way}
    n_support: ${exp.n_shot}
    n_classes: ${dataset.train_classes}
    loss: softmax

train:
  stop_epoch: 10 # Number of epochs to train
  train_batch: null # this is required to be null when using SOT, it will be set to n_way * (n_support + n_query)
  val_batch: null # this is required to be null when using SOT, it will be set to n_way * (n_support + n_query)