defaults:
  - meta_base

name: matchingnet
embed_support: true
embed_query: true

cls:
  _target_: methods.matchingnet.MatchingNet
  embed_support: ${method.embed_support}
  embed_query: ${method.embed_query}
