defaults:
  - _self_ # Prevents warning in Hydra 1.1 (https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/default_composition_order/)
  - dataset: tabula_muris
  - method: maml

exp:
  name: ??? # Experiment name
  mode: train # Whether to also train a model or just test
  n_way: 5 # Number of classes to distinguish in few-shot learning
  n_shot: 5 # Number of support samples per class to train on
  n_query: 5 # Number of query samples per class to evaluate on
  save_freq: 10 # Save the model state every save_freq epochs
  val_freq: 1 # Compute and print validation performance every val_freq epochs
  resume: false # Whether to resume training from a checkpoint
  device: "cpu" # Device to use
  log_level: "INFO" # Set logging level
  seed: 42 # Seed to use
  use_sot: True # Whether to use self-optimal transport

train:
  iter_num: 600 # Number of episodes to train few-shot methods (no effect)
  lr: 0.001 # Learning rate to use

eval:

checkpoint:
  dir: checkpoints/${exp.name}/${dataset.name}/${method.name} # Directory for checkpoint
  test_iter: best_model # Use best_model for testing
  time: latest # Use latest model

wandb:
  project: "few-shot-benchmark" # W&B project name
  entity: "metameta-learners" # W&B team name
  mode: "online" # Set to offline to stop W&B tracking

