defaults:
  - dataset: tabula_muris
  - method: maml
  - _self_

model: maml # i think this doesn't change anything, backbone is changed at dataset/*.yaml
n_way: 5
n_shot: 5
n_query: 5

mode: train

exp:
  name: ???
  save_freq: 10
  resume: false
  seed: 42
  val_freq: 1

optimizer: Adam
lr: 0.001
optimizer_cls:
  _target_: torch.optim.${optimizer}
  lr: ${lr}

checkpoint:
  dir: checkpoints/${exp.name}/${dataset.name}/${method.name}_${model}
  test_iter: best_model
  time: latest

wandb:
  project: "few-shot-benchmark"
  entity: "metameta-learners"
  mode: "online" # Can set to offline, disabled

iter_num: 600
