defaults:
  - method: null
  - dataset: null
  - _self_

group: ??? # Group the experiment should be associated to

# Experiment configuration
dataset: ??? # Dataset to use (swissprot, tabula_muris)
method: ??? # Method to use (baseline, baseline_pp, matchingnet, protonet, maml)
sot: ??? # Whether to use the SOT transform or not (true, false)
n_way: ??? # Number of classes to distinguish in few-shot learning
n_shot: ??? # Number of support samples per class to train on

n_query: 5 # Number of query samples per class to evaluate on

general:
  val_freq: 1 # Compute and print validation performance every val_freq epochs
  device: "cpu" # Device to use
  log_level: "INFO" # Set logging level
  seed: 42 # Seed to use

wandb:
  project: "few-shot-benchmark" # W&B project name
  entity: "metameta-learners" # W&B team name
  mode: "online" # Other options: `disabled`, `offline`

# Training configuration
train:
  max_epochs: 10
  lr: 0.001

eval:
  type: set # Evaluate on few-shot task
  splits: [train, val, test] # Which splits to evaluate on
  n_episodes: 600 # The number of episodes to test on (only applies to validation/ testing)

paths:
  root_dir: ${oc.env:PROJECT_ROOT}
  output_dir: ${paths.root_dir}/outputs

hydra:
  run:
    dir: ${paths.output_dir}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${hydra.run.dir}
    subdir: ${hydra.job.num}
  sweeper:
    params:
      train.lr: 0.001,0.1
